separate cbb and personal scripts

diff --git a/macos/scripts/sysinfo b/macos/scripts/sysinfo
--- a/macos/scripts/sysinfo
+++ b/macos/scripts/sysinfo
@@ -58,49 +58,49 @@ usage () {
 
 # process command line options
 
-# interactive=
-# filename=
+interactive=
+filename=
 
-#while  [[ -n "$1" ]]; do
-#	case "$1" in
-#		-f | --file)		shift
-#			filename="$1"
-#			;;
-#		-i | --interactive)	interactive=1
-#			;;
-#		-h | --help)		usage
-#			exit
-#			;;
-#		*)					usage >&2
-#			exit 1
-#			;;
-#	esac
-#	shift
-#done
+while  [[ -n "$1" ]]; do
+	case "$1" in
+		-f | --file)		shift
+			filename="$1"
+			;;
+		-i | --interactive)	interactive=1
+			;;
+		-h | --help)		usage
+			exit
+			;;
+		*)					usage >&2
+			exit 1
+			;;
+	esac
+	shift
+done
 
 # interactive mode
 
-#if [[ -n "$interactive" ]]; then
-#	while true; do
-#		read -p "Enter name of output file: " filename
-#		if [[ -e "$filename" ]]; then
-#			read -p "'$filename' exists. Overwrite? [y/n/q] > "
-#			case "$REPLY" in
-#				Y|y) break
-#					;;
-#				Q|q) echo "Program terminated."
-#					exit
-#					;;
-#				*)	continue
-#					;;
-#			esac
-#		elif [[ -z "$filename" ]]; then
-#			continue
-#		else
-#			break
-#		fi
-#	done
-#fi
+if [[ -n "$interactive" ]]; then
+	while true; do
+		read -p "Enter name of output file: " filename
+		if [[ -e "$filename" ]]; then
+			read -p "'$filename' exists. Overwrite? [y/n/q] > "
+			case "$REPLY" in
+				Y|y) break
+					;;
+				Q|q) echo "Program terminated."
+					exit
+					;;
+				*)	continue
+					;;
+			esac
+		elif [[ -z "$filename" ]]; then
+			continue
+		else
+			break
+		fi
+	done
+fi
 
 write_html_page () {
 	cat <<- _EOF_
@@ -114,23 +114,23 @@ write_html_page () {
 			<p>$TIMESTAMP</p>
 			$(report_uptime)
 			$(report_disk_space)
+            #$(report_home_space)
 		</body>
 	</html>
 	_EOF_
 	return
 }
 
-#$(report_home_space)
 # output html page
 
-#if [[ -n "$filename" ]]; then
-#	if touch "$filename" && [[ -f "$filename" ]]; then
-#		write_html_page > "$filename"
-#        write_html_page
-#	else
-#		echo "$PROGNAME: Cannot write file '$filename'" >&2
-#		exit 1
-#	fi
-#else
-	write_html_page
-#fi
+if [[ -n "$filename" ]]; then
+	if touch "$filename" && [[ -f "$filename" ]]; then
+		write_html_page > "$filename"
+        write_html_page
+	else
+		echo "$PROGNAME: Cannot write file '$filename'" >&2
+		exit 1
+	fi
+else
+   write_html_page
+fi
